title: Nurul Ferdous
description: >-
  Software Architect, DevOps, Vision, CLEF, OpenCV, ML, Algorithm,
  Big/Linked/Open Data & NLP activist. Hadoop'er, Thicker, Quicker, Picker,
  Upper & Serial Coder
social_link: twitter
social_username: ferdous
github_repo: nurul_ferdous
github_username: dynamicguy
theme_color: black
remote_theme: internet-de-france/swiss
baseurl: /nurul_ferdous
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
